import streamlit as st
import pandas as pd
import plotly.express as px
import os

# Set page configurations
st.set_page_config(page_title="Amazon AOP Retail Logistics Dashboard", layout="wide")

st.title("📦 Retail Supply Chain & Operations Performance Dashboard")
st.markdown("### Amazon Analytics, Operations, and Programs (AOP) - Case Study Profile")
st.markdown("---")

# Load the data generated by app.py
csv_path = 'retail_operations_data.csv'
if not os.path.exists(csv_path):
    st.error(f"❌ Data file '{csv_path}' not found! Please run 'python app.py' first to generate your underlying dataset.")
else:
    df = pd.DataFrame(pd.read_csv(csv_path))
    
    # 1. TOP LEVEL METRICS SUMMARY CARDS
    total_orders = len(df)
    total_sales = df['Sales'].sum()
    otdr = (df['DeliveryStatus'] == 'On-Time').sum() / total_orders * 100
    return_rate = (df['ReturnRequested'] == 'Yes').sum() / total_orders * 100
    
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Volume Processed", f"{total_orders:,} Orders")
    col2.metric("Gross Fulfilled Value", f"${total_sales:,.2f}")
    col3.metric("On-Time Delivery Rate (OTDR)", f"{otdr:.2f}%")
    col4.metric("Customer Return Rate (RR)", f"{return_rate:.2f}%")
    
    st.markdown("---")
    
    # 2. INTERACTIVE VISUAL ANALYSIS CORES
    chart_col1, chart_col2 = st.columns(2)
    
    with chart_col1:
        st.subheader("Fulfillment Delivery Status Breakdown")
        status_counts = df['DeliveryStatus'].value_counts().reset_index()
        status_counts.columns = ['Status', 'Count']
        fig_status = px.pie(status_counts, values='Count', names='Status', 
                            color_discrete_sequence=['#2ecc71', '#e74c3c', '#f1c40f'])
        st.plotly_chart(fig_status, use_container_width=True)
        
    with chart_col2:
        st.subheader("Category Performance Analysis Matrix")
        summary = df.groupby('Category').agg(
            Total_Orders=('OrderID', 'count'),
            On_Time_Deliveries=('DeliveryStatus', lambda x: (x == 'On-Time').sum())
        ).reset_index()
        summary['On_Time_Delivery_Rate_%'] = (summary['On_Time_Deliveries'] / summary['Total_Orders']) * 100
        
        fig_bar = px.bar(summary, x='Category', y='On_Time_Delivery_Rate_%',
                         labels={'On_Time_Delivery_Rate_%': 'On-Time Rate %'},
                         color='Category', color_discrete_sequence=px.colors.qualitative.Pastel)
        st.plotly_chart(fig_bar, use_container_width=True)
